README.md
docs/adr/01-architecture-pattern.md
docs/adr/02-api-gateway.md
packages/cdk/lib/__snapshots__/pressreader.test.ts.snap
packages/cdk/lib/pressreader.ts
packages/pressreader/src/util.ts

This change adds an API Gateway Rest API, and utilises the S3 integration to allow serving files from the S3 bucket the scheduled lambda is writing to. This allows us to move towards removing public read buckets elsewhere.
There is [an ADR added in this change](https://github.com/guardian/pressreader/blob/rk/add-api-gateway/docs/adr/02-api-gateway.md) that describes the justification for this decision.
Data from the API can be requested:
```sh
# Endpoint takes requests in the for /data/:date
curl -H "x-api-key: not-a-real-api-key" https://pressreader.gutools.co.uk/data/20230503
```
Eventually Pressreader is able to use this API, and we can avoid any use of public S3 buckets.
Leak of an API key could result in unexpected spike in API usages, however request rates are throttled.

Add API Gateway S3 integration

---

packages/pressreader/src/config.ts
packages/pressreader/src/types/PressReaderTypes.ts
packages/pressreader/src/types/PressedFrontTypes.ts

- Add types for the expected output shape for the pressreader lambda. Also renames the existing `Section` type to make it clearer that it holds config for a section, not the output content for a section.
- Exports `ContentType`. It isn't actually imported in the current branch, but this PR is cherry-picked from a much larger PR where it will be imported. (I'm trying to reduce the number of files that are changed in that main PR.)
- Adds a couple of extra sections to the config fixture; this enables us to test with CAPI sources and deduping etc.

Rename and add output types

---

package-lock.json
packages/pressreader/package.json
packages/pressreader/src/handler.ts
packages/pressreader/src/processEdition.ts
packages/pressreader/src/typePredicates.ts
packages/pressreader/src/types/CapiTypes.ts
packages/pressreader/src/types/PressReaderTypes.ts

An initial pass at implementing the business logic for the pressreader job.
1. Take a config file that specifies a list of 'sections'.
2. Fetch the fronts collections and CAPI backfill searches for each section.
3. Fetch details for each article that was returned by step (2).
4. Check the articles for eligibility:
- Exceeds a minimum wordcount.
- Was published in the last 24 hours.
- Doesn't include any 'banned' tags.
- Hasn't already been included in another section of this edition.
It then returns a list of sections and article ids, to be saved to S3 by the handler function.
- Set a CAPI api key in `resources.sh` (but make sure not to commit this!)
- Run `npm run dev`.
- Output should be generated for the example config in `config.ts`.
This is part of migrating the existing service from …

Add business logic to handler

---

packages/pressreader/src/meetsInclusionCriteria.test.ts
packages/pressreader/src/processEdition.ts
packages/pressreader/src/types/CapiTypes.ts

Add automated tests for the main cases covered by the `meetsInclusionCriteria` function.
While adding these I realised that there was an error in the CAPI model types which was leading to the `webPublicationDate` of articles being accessed incorrectly. This commit also fixes that bug.
Run `npm run test` in the terminal.
The logic for this function can be changed in the future with greater confidence.

Tests: article inclusion function

---

docs/README.md
packages/cdk/lib/__snapshots__/pressreader.test.ts.snap
packages/cdk/lib/pressreader.ts

Adds monitoring to this lambda to notify `newsroom.resilience+alerts@guardian.co.uk` if there is an error in 2 consecutive runs of the lambda.
The error state of the alarm can be set artificially to test if the expected email gets sent.
We are notified of errors in `pressreader` runs and can fix things before people notice anything wrong.

Add monitoring config, update docs

---

packages/pressreader/src/typePredicates.test.ts
packages/pressreader/src/typePredicates.ts

Unit testing some of the more complicated type predicate functions. nb. these functions don't try to check every expected property of the relevant types. Rather, it takes the approach of verifying that some key indicative properties are present, and trusts that the CAPI models will be accurate for the rest of the properties if the tested properties are present.
I did want to check that they wouldn't crash if given unexpected inputs though.
`npm run test`

Unit Tests: Type Predicates

---

packages/pressreader/src/util.ts

Use `getDate` instead of `getDay` for the name of the JSON file that we're saving to S3.
Docs for the JS Date function:
```ts
/** Gets the day-of-the-month, using local time. */
getDate(): number;
/** Gets the day of the week, using local time. */
getDay(): number;
```
I'm still not sure how we want to handle timezone localisation, but I think that's a separate issue.
We keep the same filename format that's used in the existing system.

Use correct function for day-of-month

---

packages/pressreader/src/config.ts
packages/pressreader/src/types/PressReaderTypes.ts

I believe that this will be the most intuitive way of indexing collections for developers, and fits the defaults of JavaScript.
Determining the indexes for a collection requires looking at the JSON representation of a front page, so for the time being it seems reasonable to assume that people editing this config will be familiar with the zero-index convention.
The actual code shouldn't need to change, because I'd been working on the assumption that the indexes start at 0. So this config change should also bring the output closer into line with the existing script.

Refactor collectionIndexes to start at 0

---

packages/pressreader/src/editionConfigs/usConfig.ts

Update the US config to match that provided by @blishen, remembering to zero index `collectionIndexes` and remove API keys and CAPI host name.
Deploy this change, observe the output provided when the lambdas are triggered.
Pressreader are able to consume US data.
This file when used by the previous service used to contain API keys we don't want to be publicly visible! They have all been removed.

Update US config

---

.github/workflows/ci.yml
packages/cdk/bin/cdk.ts
packages/cdk/lib/__snapshots__/pressreader.test.ts.snap
packages/cdk/lib/pressreader.test.ts
packages/cdk/lib/pressreader.ts
packages/pressreader/src/constants.ts
packages/pressreader/src/editionConfigs/ausConfig.ts
packages/pressreader/src/editionConfigs/index.ts
packages/pressreader/src/editionConfigs/usConfig.ts
packages/pressreader/src/handler.ts
packages/pressreader/src/util.ts
packages/shared-types.ts

Configure a lambda per config / write destination in order to run the "new" and "old" paths in parallel and at the same time provide a way to publish different editions.
Deploy this to INFRA and ensure that the infrastructure deploys, the lambdas run when triggered via a test run, and that the expected data is available at the appropriate endpoints with the API key retrievable from API gateway:
- https://pressreader.gutools.co.uk/US/20230606
- https://pressreader.gutools.co.uk/AUS/20230606
Pressreader are able to use the data provided by the lambda to produce print on demand papers, and eventually can use the API gateway endpoints without further work.
We need to check that the data the new method produces is functionally substitutable from the old data, and that we will be alerted if …

Update infrastructure setup to create lambda per config

---

packages/cdk/bin/cdk.ts

Remove 'testing' prefix from AUS-old path
In effect this will 'launch' the new version of the AUS lambda, by
directing its outputs to the same place that the existing AppleScript
version does currently.

Launch AUS lambda, writing to legacy location

---

packages/pressreader/src/util.ts

This fixes an issue where if `prefixPath` is empty a leading slash is appended to the path written to S3 resulting in "/" becoming the "folder name" for the object 😖 
Files are published to their correct location with and without a prefix.

If prefixPath is empty, just use objectLocation

---

packages/cdk/bin/cdk.ts

Remove 'testing' prefix from US-old path
After this is merged we should:
Follows: https://github.com/guardian/pressreader/pull/22
This will 'launch' the new version of the US lambda, by
directing its outputs to the same place that the existing AppleScript
version does currently.

Launch US lambda, writing to legacy location

---

docs/README.md
docs/pressreader-config.md

This change adds some documentation created by David B that describes how the config affects what is published by the Pressreader lambdas.
[Read the documentation.](https://github.com/guardian/pressreader/blob/rk/config-docs/docs/pressreader-config.md)
Does the documentation make sense? Could someone new to the project use it to make sensible changes?

Adds some documentation on config

---

packages/pressreader/src/editionConfigs/ausConfig.ts
packages/pressreader/src/editionConfigs/usConfig.ts

Use https for API requests instead of http. @andrew-nowak noticed that we were using http, but that the API supports https as well. Using https is more secure.
Closes #30

Use https for API calls

---

docker-compose.yml
localstack/resources.sh
packages/pressreader/package.json
packages/pressreader/src/editionConfigs/index.ts
packages/pressreader/src/handler.ts

This change fixes a bug where the pressreader lambda could not be run locally:
```
➜  pressreader git:(main) npm run dev
> pressreader@1.0.0 dev
> ts-node-dev --respawn src/handler.ts
[INFO] 10:53:12 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 4.9.5)
Error: Cannot find module 'packages/shared-types'
Require stack:
- /Users/Robert_kenny/workspace/pressreader/packages/pressreader/src/handler.ts
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
at Function.Module._load (node:internal/modules/cjs/loader:885:27)
at Module.require (node:internal/modules/cjs/loader:1105:19)
at require (node:internal/modules/cjs/helpers:103:18)
at Object.<anonymous> (/Users/Robert_kenny/workspace/pressreader/packages/pressreader/src/handler.ts:1:1)
at …
```

Fix running pressreader lambda locally

---

packages/cdk/lib/__snapshots__/pressreader.test.ts.snap
packages/cdk/lib/pressreader.ts
packages/pressreader/src/constants.ts

Adds the infrastructure to allow us to send alerts when we spot a failure to lookup a collection from the config:
1. A new metric, called `CollectionLookupFailure`.
2. An alarm which will notify the existing email alert SNS topic for this project.
3. Make a new environmental variable available to the Lambda handler, so that it can address the new metric.
Actual use of the new metric and alarm will be added in a subsequent PR.
Look at the diffs in the config output as part of our snapshot test. Beyond that, I'm not sure we can test this properly without merging and deploying it, because we don't have a CODE stage as things stand.
We will be able to receive alerts when the lambda tries to look up collections which don't exist.

Add Cloudwatch alarm for lookup failures

---

packages/cdk/lib/__snapshots__/pressreader.test.ts.snap
packages/cdk/lib/pressreader.ts

We are seeing alarms go off as we error for even a single error. In order to tolerate transitory errors we can try more often and fail only when we see multiple errors.
Deploy the change, watch the CloudWatch alarms to ensure they are behaving as expected.
We only get alarm emails when there is a real problem we need to take action on.

Run lambda more often, and tolerate more errors

---

packages/cdk/bin/cdk.ts
packages/cdk/lib/__snapshots__/pressreader.test.ts.snap
packages/cdk/lib/pressreader.test.ts
packages/cdk/lib/pressreader.ts

Reverts guardian/pressreader#38
RiffRaff [deployment is failing](https://riffraff.gutools.co.uk/deployment/view/55cd9b76-d509-48ef-80e1-4d4e7eac72df) and there isn't enough time to properly investigate this today, so I think it's best to try and leave `main` in a good state over night.

Revert "Add CODE stage"

---

packages/cdk/lib/__snapshots__/pressreader.test.ts.snap
packages/cdk/lib/constructs/GuLambdaErrorPercentageAlarm.ts
packages/cdk/lib/pressreader.ts

This change updates the `GuLambdaErrorPercentageAlarm` construct to take into account the error monitoring requirements of scheduled lambdas.
`GuLambdaAlarmProps` is updated to include `lengthOfEvaluationPeriod` and `numberOfEvaluationPeriodsAboveThresholdBeforeAlarm` so that alarms can be set which take into account the cadence at which a scheduled lambda runs.
```ts
interface GuLambdaAlarmProps extends GuLambdaErrorPercentageMonitoringProps {
lambda: GuLambdaFunction;
lengthOfEvaluationPeriod?: Duration;
numberOfEvaluationPeriodsAboveThresholdBeforeAlarm?: number;
}
```
For example, in this case for a lambda that runs every 15 minutes we want to know if it fails on twice concurrent runs, we would set:
```ts
const alarmProps = {
toleratedErrorPercentage: 1,
lengthOfEvaluationPeriod: …
```

Custom monitoring for scheduled lambda

---

.gitignore
packages/pressreader/package.json
packages/pressreader/src/editionConfigs/ausConfig.ts
packages/pressreader/src/editionConfigs/usConfig.ts
packages/pressreader/src/handler.ts
packages/pressreader/src/processEdition.ts
packages/pressreader/src/processFrontData.test.ts
packages/pressreader/src/types/PressReaderTypes.ts

Refactors the fronts config to specify collections by `id` instead of name or index. We expect the `id` to be more stable over time than name and (especially) index. I've continued to include the expected display name of the collection in the config, though, to preserve a record of the intended target. This will allow us to log when a collection name changes, which could be used as a prompt to check that the collection is still appropriate for inclusion.
This should allow us to add an alarm when an expected collection id is not found on a front page. This will allow incremental review of the configs as and when there's a breaking change in the fronts. This should mean that we fix issues earlier, and will also hopefully be more efficient than periodic general reviews where context may be …

Look up collections via id instead of name/index

---

docs/README.md
package-lock.json
packages/cdk/lib/__snapshots__/pressreader.test.ts.snap
packages/cdk/lib/pressreader.ts
packages/pressreader/package.json
packages/pressreader/src/aws.ts
packages/pressreader/src/constants.ts
packages/pressreader/src/handler.ts

- Separate SNS topic and email subscription for 'alarms' vs 'notifications' (the latter being non-critical).
- Add stage to the topics for both subscriptions, and also to the custom metric for collection lookup failures. This is so that publishing to the metric won't result in alarms for *both* stages; instead it should only alarm for the stage that the metric was published from.
- Pass metric publishing function from the handler to the processing function which has the information needed to trigger the alarm.
- Document this notification in the project README.
We find out about config issues when they happen and review them incrementally, rather than waiting for someone to complain because so many bugs have accumulated.
If we're getting far too many emails then we should review this …

Wire up collection lookup failure alarm

---

packages/pressreader/src/editionConfigs/ausConfig.ts
packages/pressreader/src/editionConfigs/usConfig.ts
packages/pressreader/src/processEdition.ts
packages/pressreader/src/processFrontData.test.ts
packages/pressreader/src/types/PressReaderTypes.ts
packages/pressreader/src/types/PressedFrontTypes.ts

Index-based lookups were previously removed in #39 in favour of looking up collections by their id. However, we've since found out that there are some valid cases for looking up a collection by index instead of id. In particular, the editors want to be able to pull stories from the first collection on some pages, as new temporary collections are sometimes used to display important stories at the top of the page.
Because the lookup logic was refactored in #39 in order to add id-based lookup, this PR doesn't just revert the previous change.
I've added a unit test for index-based lookups. One could also run the lambda either locally or in CODE and check the output.
There's some potential for index-based lookups to target collections that we wouldn't have wanted to include, but this form of …

Add index-based lookup for collections

---

packages/pressreader/src/checkArticlesForSection.test.ts
packages/pressreader/src/meetsInclusionCriteria.test.ts
packages/pressreader/src/processEdition.ts
packages/pressreader/src/typePredicates.ts
packages/pressreader/src/types/CapiTypes.ts
packages/pressreader/src/types/PressReaderTypes.ts

- Restructure the way Sections are processed, to allow us to filter articles by tone tags within a given section. (The existing 'bannedTags' list applies to the whole edition, rather than specific sections.)
- Add unit tests for the `checkArticlesForSection` function.
- Refactor the `Tag` type and `CapiItemResponse` type because the one we were importing from the CAPI types library didn't represent the tag 'type' (e.g. 'keyword', 'tone') accurately.
We can implement the new config that has been passed to us by Editorial, which includes tone filters.

Add tone filters to Section config

---

.github/dependabot.yml

Adds Dependabot settings to get it to group dependency update PRs, instead of raising one for each dependency. This adds two groups: `cdk-dependencies` and `non-cdk-dependencies`. [Documentation for the 'groups' setting](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups).
I've linted the YAML changes. Beyond that, we may need to wait until Dependabot raises a new dependency PR to see whether it works as intended. If we're keen to do so we could temporarily make it raise them more often. 
Spend less time reviewing and merging dependency PRs, more easily keep deps up to date. Doesn't rely on custom workflows or third party GHA actions.
Worth noting that this feature is officially [in …

Add dependency groups (cdk and non-cdk)

---

packages/pressreader/src/editionConfigs/ausConfig.ts
packages/pressreader/src/editionConfigs/usConfig.ts

Config updates: US & AUS

---

packages/cdk/lib/__snapshots__/pressreader.test.ts.snap
packages/cdk/lib/pressreader.ts

Following https://github.com/guardian/cdk/pull/1906 a small refactor to use monitoring provided by `GuFunction`. Makes the CDK infra slightly less surprising.
Less surprising CDK code, continued alarms when there are problems.
This change will re-create the CloudWatch alarms, but should not impact our ability to continue to receive alerts.

Move monitoring inside lambda

---

packages/cdk/lib/__snapshots__/pressreader.test.ts.snap
packages/cdk/lib/pressreader.ts

This change makes the alarm require errors in 3 evaluation periods rather than 2. We have recently seen a couple of instances of false alarms where the APIs pressreader depends on are unavailable for >30 minutes with no "business value" impact on this service.
We should make the alarms less sensitivity to reduce the risk of ignoring things in the future if these periods of temporary unavailability continue.
We should only see alarms where investigation and action is required.

Decrease alarm sensitivity

---

packages/pressreader/src/editionConfigs/usConfig.ts

Add the `us-news/series/guardian-us-briefing` tag to the `bannedTags` list. The articles with this tag belong to the 'first thing' series, which is a newsletter so shouldn't be included in Pressreader editions.
The `bannedTags` functionality was already implemented so hopefully this will be a straightforward change.

Add 'first-thing' tag to bannedTags

---

packages/cdk/bin/cdk.ts
packages/cdk/lib/__snapshots__/pressreader.test.ts.snap
packages/cdk/lib/pressreader.test.ts
packages/cdk/lib/pressreader.ts

Use a cron expression to schedule the lambdas, so that we can run them at a slight offset from each other. The intention is that it should reduce the chance of hitting the rate limit on the shared CAPI key.
Deploy and check that it runs on the intended schedule.
Fewer rate limit issues.

Offset lambda schedules

---

packages/cdk/jest.setup.js
packages/pressreader/src/editionConfigs/ausConfig.ts

Set curly apostrophe to resolve name mismatch

---

packages/cdk/bin/cdk.ts
packages/cdk/lib/__snapshots__/pressreader.test.ts.snap
packages/cdk/lib/pressreader.ts

Two main changes:
1. Each of the four lambdas created by the CDK has its own Secrets Manager location for its CAPI token.
2. The 'new' lambdas (which serve their output via API Gateway) have their schedules adjusted to run less often.
* nb. The monitoring config assumes that the lambdas are run every 15 minutes, so I've made these run 4 times per hour, but only for one hour during each day.
We're hitting the CAPI rate limit, and also using energy and money unnecessarily by running all four lambdas so regularly, while only two are actually being used.
We'll need to manually fill in the new Secrets Manager values after deployment.

Separate CAPI secrets and run the new lambdas less often

---

packages/cdk/bin/cdk.ts

Run the 'new' lambdas every hour, as well as the old ones. Pressreader will be switching over from one to the other soon, but we're not sure when, so we want to make sure that there's data available via both methods temporarily. I'm increasing the rate limit on the CAPI tokens temporarily, until we switch the old lambdas off.

Run all PROD lambdas every hour

---

.github/dependabot.yml

Remove `typescript` from the dependabot grouping. We can't update ts independently of various `@guardian/` packages, so CI always fails when typescript is included in a group of dependency updates.

Remove typescript from dependabot groupings

---

packages/pressreader/src/editionConfigs/ausConfig.ts

There's a new collection being used for the 'News Extra' section on the AU headline now. This updates the AU config with the new collection id.

Update with new 'news extra' collection id

---

packages/pressreader/src/example.test.ts
packages/pressreader/src/processFrontData.test.ts
packages/pressreader/src/typePredicates.test.ts
packages/pressreader/src/typePredicates.ts

- Check all required fields in the CAPI item response, as part of the `isCapiItemResponse` type predicate.
- Delete an unused example test file.
- Fix a typo in a test case.
This is in preparation for #120, where we want to know that we have all required fields in the CAPI item data before processing it.

Improve CAPI Item type predicate checks and misc refactors

---

packages/pressreader/src/fetchArticleData.test.ts
packages/pressreader/src/processEdition.ts
packages/pressreader/src/types/CapiTypes.ts

Pass a custom `validateStatus` function to `axios.get`, which treats 404 as a valid status. This prevents axios from erroring on a 404 code.
We sometimes get invalid or outdated CAPI ids from the fronts API, and there's nothing we can do about it, so it's better to just log the issue and keep moving without the article in question.
Fewer un-actionable error alarms triggered. Less noise 👍

Don't error if CAPI article lookup returns 404

---

docs/README.md

Adds more information on collection lookup failure alarms.
- Does this seem accurate and understandable?
- Is there anything important missing?

Docs: Elaborate on lookup failure notifications

---

packages/pressreader/src/editionConfigs/ausConfig.ts

We've been getting `CollectionNotFound` alarms today, and [logs show that it's for the Women's World Cup 2023 collection](https://logs.gutools.co.uk/s/newsroom-resilience/goto/ec311400-112b-11ef-bd02-15bf929da514) on the Australia sports front.
There are no logs showing a name mismatch for this collection, prior to its removal, so it seems surprising that this 2023 event would only just have been removed. However, it does make sense that it wouldn't be included in the config anyway (and I can see from logs that we were pulling in and then discarding a lot of old world cup articles, prior to receiving this alarm) so it seems like a low risk change to just remove it.
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#scr …

Remove world cup 2023 collection, as it's no longer maintained

---

package-lock.json
package.json
packages/cdk/cdk.json
packages/cdk/package.json

As in the title, but also finishes replacing ts-node with tsx, started in #171 , and resolves reported CVE from `braces` by bumping

Move some build-time-only deps into devdeps

---

packages/pressreader/src/editionConfigs/usConfig.ts

There's a new Opinion collection on the `/us/environment` front.

Update us/environment Opinion collection id

---

package-lock.json
packages/pressreader/package.json

Resolves this warning from jest:
```
jest-haste-map: Haste module naming collision: pressreader
The following files share their name; please adjust your hasteImpl:
* <rootDir>/packages/pressreader/package.json
* <rootDir>/package.json
```
Likely makes no observable difference, but one less warning is one less warning

change submodule name to avoid name collision warning from jest

---

packages/cdk/lib/__snapshots__/pressreader.test.ts.snap
packages/cdk/lib/pressreader.ts
packages/pressreader/src/processEdition.ts

- Add more and structured data to missing collection logging
- Also adjust the logFormat for the lambdas to Text, as this is what's required for our log ingestion pipeline to be able to handle (stringified) JSON as structured fields.
- Add ok action to collections alarm
The extra logging and the ok action should make it quicker to diagnose what's going on when we see a missing collection alarm, both helping us to see when the issue is just transitory, and also making it easier to identify which collection has gone missing. …

Add more and structured data to missing collection logging

---

packages/pressreader/src/editionConfigs/ausConfig.ts

* A new collection is being used for the `Headlines` container, so update its id.
* `News Extra` has been replaced by `Federal election` until the federal election (in a month), so temporarily swap them in the config.
I've run these changes past Dave E. in Aus.
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/ …

Update AUS Headlines collection id, temporarily swap out News Extra for Federal election

---

packages/pressreader/src/editionConfigs/ausConfig.ts
packages/pressreader/src/editionConfigs/usConfig.ts

These don't want to be included in the feed

Exclude articles with Newsletters tone 

---

packages/pressreader/src/editionConfigs/ausConfig.ts
packages/pressreader/src/editionConfigs/usConfig.ts

Updates a number of containers on the US and AU network fronts, in response to a number of collections being swapped out on these fronts.
This has been checked with JW in Licensing.

Update configs for new fronts

---

packages/pressreader/src/editionConfigs/ausConfig.ts
packages/pressreader/src/editionConfigs/usConfig.ts

- One probable typo (Opinion)
- One that I think was replaced a little while ago but I missed it (Federal election)

Fix AUS collection ids

---

packages/pressreader/src/editionConfigs/ausConfig.ts
packages/pressreader/src/editionConfigs/usConfig.ts

Fix US config

---

packages/pressreader/src/editionConfigs/usConfig.ts

- Privacy and Devices have been removed
- News has been replaced by a new Technology collection
- Games has a new collection id
Changes checked with JW from licensing and tested in CODE 👍 

Update US Technology collections
